config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions'
  }
  root "home#index"
  resources :users
  resources :votes, only: :create
  namespace :admin do
    resources :canlidates
    resources :votes, only: :index
  end

end

app/views/shared/_award_detail.html.erb
<% award.canlidates.each do |canlidate| %>
<div class="team-adward">
  <div class="team-img" style="background: url('<%= canlidate.banner_url %>')"></div>
  <div class="team-content">
    <p class="team-name"><%= canlidate.name %></p>
    <p class="team-subTitle"><span><%= canlidate.start %></span></p>
    <div class="team-text"><%= canlidate.description.try(:html_safe) %></div>
    <a class="seeMore" rel="team<%= canlidate.id %>">See more</a>
<% if current_user %>
  <% if current_user.canlidate_voted?(canlidate) %>
    <div class="vote active">voted</div>
  <% else %>
    <div class="vote"><%= link_to 'Vote now', votes_path(canlidate_id: canlidate.id), method: :post, remote: true, style: "color: white;" %></div>
  <% end %>
<% end %>
  </div>
  <div class="clr"></div>
 </div>
<% end %>
<div class="clr"></div>
<div class="icon-close"></div>

app/views/shared/_canlidate_popup.html.erb
<% Canlidate.all.each do |canlidate| %>
    <div class="popup-form detail-team" id="team<%= canlidate.id %>">
      <div class="d-team-adward">
        <div class="d-team-img" style="background: url('<%= canlidate.banner_url %>')"></div>
        <div class="d-team-content">
          <p class="d-team-name"><%= canlidate.name %></p>
          <p class="d-team-subTitle"><span><%= canlidate.start %></span></p>
          <div class="team-text"><%= canlidate.description.try(:html_safe) %></div>
<% if current_user %>
  <% if current_user.canlidate_voted?(canlidate) %>
              <div class="vote active">voted</div>
  <% else %>
              <div class="vote"><%= link_to 'Vote now', votes_path(canlidate_id: canlidate.id), method: :post, style: "color: white;" %></div>
  <% end %>
<% end %>
        </div>
        <div class="clr"></div>
      </div>
      <div class="close-form"></div>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>