config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions'
  }
  root "home#index"
  resources :users
  resources :votes, only: :create
  namespace :admin do
    resources :canlidates
    resources :votes, only: :index
  end

end

app/models/canlidate.rb
class Canlidate < ActiveRecord::Base

  belongs_to :award
  has_many :votes

  mount_uploader :banner, AvatarUploader
end

app/controllers/admin/canlidates_controller.rb
class Admin::CanlidatesController < ApplicationController

  layout "admin_layout"
  http_basic_authenticate_with name: "Framgia",
    password: "123@123a"
  before_action :set_canlidate, only: [:show, :edit, :update, :destroy]

  # GET /admin/canlidates
  # GET /admin/canlidates.json
  def index
    @canlidates = Canlidate.all
  end

  # GET /admin/canlidates/1
  # GET /admin/canlidates/1.json
  def show
  end

  # GET /admin/canlidates/new
  def new
    @canlidate = Canlidate.new
  end

  # GET /admin/canlidates/1/edit
  def edit
  end

  # POST /admin/canlidates
  # POST /admin/canlidates.json
  def create
    @canlidate = Canlidate.new(canlidate_params)

    respond_to do |format|
      if @canlidate.save
        format.html { redirect_to admin_canlidate_path(@canlidate), notice: 'Canlidate was successfully created.' }
        format.json { render :show, status: :created, location: @canlidate }
      else
        format.html { render :new }
        format.json { render json: @canlidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/canlidates/1
  # PATCH/PUT /admin/canlidates/1.json
  def update
    respond_to do |format|
      if @canlidate.update(canlidate_params)
        format.html { redirect_to admin_canlidate_path(@canlidate), notice: 'Canlidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @canlidate }
      else
        format.html { render :edit }
        format.json { render json: @canlidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/canlidates/1
  # DELETE /admin/canlidates/1.json
  def destroy
    @canlidate.destroy
    respond_to do |format|
      format.html { redirect_to admin_canlidates_url, notice: 'Canlidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_canlidate
      @canlidate = Canlidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canlidate_params
      params.require(:canlidate).permit(:name, :description, :banner, :award_id, :start)
    end
end

app/helpers/admin/canlidates_helper.rb
module Admin::CanlidatesHelper
end

app/views/admin/canlidates/_form.html.erb
<%= form_for [:admin, @canlidate] do |f| %>
  <% if @canlidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canlidate.errors.count, "error") %> prohibited this canlidate from being saved:</h2>

      <ul>
      <% @canlidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td>Name</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td>Start</td>
      <td><%= f.text_field :start %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td><%= f.text_area :description, cols: 50, rows: 30 %></td>
    </tr>
    <tr>
      <td>Banner</td>
      <td><%= f.file_field :banner %></td>
    </tr>
    <tr>
      <td>Award</td>
      <td><%= f.collection_select :award_id, Award.all, :id, :name %></td>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/canlidates/edit.html.erb
<h1>Editing Admin Canlidate</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_canlidate_path(@canlidate) %> |
<%= link_to 'Back', admin_canlidates_path %>

app/views/admin/canlidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Canlidates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @canlidates.each do |canlidate| %>
      <tr>
        <td><%= canlidate.id %></td>
        <td><%= canlidate.name %></td>
        <td><%= link_to 'Show', admin_canlidate_path(canlidate) %></td>
        <td><%= link_to 'Edit', edit_admin_canlidate_path(canlidate) %></td>
        <td><%= link_to 'Destroy', admin_canlidate_path(canlidate), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Canlidate', new_admin_canlidate_path %>

app/views/admin/canlidates/new.html.erb
<h1>New Admin Canlidate</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_canlidates_path %>

app/views/admin/canlidates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_canlidate_path(@canlidate) %> |
<%= link_to 'Back', admin_canlidates_path %>